blank_issues_enabled: false
contact_links:
  - name: Community Discussion
    url: https://coretalk.space
    about: Discussion about Core Blockchain.
  - name: Quick Start
    url: https://github.com/core-coin/wallet-generator#start-the-application
    about: Manual - how to start the wallet.
  - name: All releases
    url: https://github.com/core-coin/wallet-generator/releases
    about: You can download the release for x86_64 architecture.
