name: Feature request
description: Suggest an idea for this project.
title: "[FEATURE] "
labels:
  - feature
assignees:
  - raisty
body:
  - type: markdown
    attributes:
      value: |
        Suggest an idea for this project and developers will consider the integration.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Is your feature request related to a problem? Please describe.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: Describe the solution you'd like.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Describe alternatives you've considered.

  - type: textarea
    id: implementation
    attributes:
      label: Implementation
      description: Describe implementation with example of the code.

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Please, place additional content or screenshots.
